article/accounts/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views  # ???
from .decorators import anonymous_required

from .views import MyRegistrationView, MyActivationView

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'template_name': 'accounts/logout.html', 'next_page': 'sth:index'},
        name="logout"),
    url(r'^reset/$', auth_views.password_reset, {'template_name': 'accounts/reset.html',
                                                 "email_template_name": 'accounts/reset_email.html',
                                                 "subject_template_name": 'accounts/reset_subject.txt',
                                                 "post_reset_redirect": reverse_lazy('accounts:reset_done')},
        name='reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, {'template_name': 'accounts/reset_done.html'},
        name='reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm, {"template_name": 'accounts/reset_confirm.html',
                                            "post_reset_redirect": reverse_lazy('accounts:login')},
        name='reset_confirm'),
]


registrationpatterns = [
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           MyActivationView.as_view(),
                           name='registration_activate'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),

                       url(r'^register/$', MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^checkavailability/$', views.checkavailability),
                       ]

urlpatterns += registrationpatterns

article/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^badabum/', admin.site.urls),
    url(r'', include('sth.urls', namespace='sth')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^info/', include('info.urls', namespace='info')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/sth/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'articles/$', views.article_list, name="articles"),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[\w-]+)$', views.article_comments, name='article_comments'),
    url(r'^ajaxrating/$', views.ajaxrating, name="ajaxrating"),
]

article/accounts/models.py
from django.db import models

# Create your models here.

article/accounts/forms.py
from django import forms
from registration.forms import RegistrationFormUniqueEmail
from django_countries import countries
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.password_validation import NumericPasswordValidator, MinimumLengthValidator
from settings.base import AUTH_PASSWORD_VALIDATORS
from django.core.exceptions import ImproperlyConfigured, ValidationError


COUNTRY_CHOICES = [('', 'Select country')] + list(countries)


def validate_minimal_length(password):
    min_length = -1
    for validator in AUTH_PASSWORD_VALIDATORS:
        if validator["NAME"] == "django.contrib.auth.password_validation.MinimumLengthValidator":
            min_length = validator["OPTIONS"]['min_length']
    if 0 < len(password) < min_length:
        raise ValidationError(
                _("This password is too short. It must contain at least %(value)s characters."),
                code='password_too_short', params={'value': min_length}
            )


def validate_numeric_password(password):
    if password.isdigit():
        raise ValidationError(
            _("This password is entirely numeric."),
            code='password_entirely_numeric',
        )


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput,
        validators=[validate_numeric_password, validate_minimal_length])

    country = forms.ChoiceField(choices=COUNTRY_CHOICES)  # for inserting user_profile

article/accounts/views.py
import re
import json

from django.forms import ValidationError
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext
from django.views.decorators.cache import cache_control
from django.utils.decorators import method_decorator

from .decorators import anonymous_required
from .forms import UserProfileRegistrationForm
from users.models import UserProfile
from registration.backends.default.views import RegistrationView, ActivationView
from registration.forms import RegistrationFormUniqueEmail


def checkavailability(request):  # check for availability and also some email validation
    # is_present: did user enter any value
    # email:
    response_dict = {}
    if "field_id" in request.POST:
        if request.POST.get('field_id') == 'id_email':  # check which field are we checking
            response_dict.update({'email_free': 1, "is_valid": 1, "value_present": 1})  # 1 ok
            email = request.POST.get("user_input")
            if len(email) == 0:
                response_dict.update({"value_present": 0})
            email_search = User.objects.filter(email__iexact=email)
            if len(email_search) != 0:
                response_dict.update({'email_free': 0})  # 0 not ok

            try:  # here we also do email validation so we do not have to type the same validator in javascript
                validate_email(email)
            except ValidationError:
                response_dict.update({"is_valid": 0})
        elif request.POST.get('field_id') == 'id_username':  # here we are checking username
            response_dict.update({'username_free': 1, "is_valid": 1, "value_present": 1})
            username = request.POST.get("user_input")
            if len(username) == 0:
                response_dict.update({"value_present": 0})
            username_search = User.objects.filter(username__iexact=username)
            if len(username_search) != 0:
                response_dict.update({'username_free': 0})

            if not re.match(r'^[\w.@+-]+$', username):  # check for the correct characters
                response_dict.update({"is_valid": 0})
        return HttpResponse(json.dumps(response_dict), content_type='application/javascript')
    else:
        return render(request, 'accounts/registration_form.html', context_instance=RequestContext(request))


@method_decorator(anonymous_required, name='dispatch')
@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class MyRegistrationView(RegistrationView):
    template_name = 'accounts/registration_form.html'
    success_url = "accounts:registration_complete"
    form_class = UserProfileRegistrationForm

    def register(self, form_class):
        new_user = super(MyRegistrationView, self).register(form_class)
        user_profile = UserProfile(user=new_user, country=form_class.cleaned_data['country'])
        user_profile.save()  # can be changed to new_user.save() if we create post_save signal on user
        return new_user


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class MyActivationView(ActivationView):
    #failed activation template is registration/activate.html, which is also a template_name value in parent class
    def get_success_url(self, user):
        return ('accounts:registration_activation_complete', (), {})

article/accounts/templates/accounts/activation_email.html
{% load i18n %}
<html lang="en">

<head>
    <title>{{ site.name|title }} {% trans "registration" %}</title>
</head>

<body>
<p>
    You (or someone pretending to be you) have asked to register an account at
    {{ site.name|capfirst }}.  If this wasn't you, please ignore this email
    and your address will be removed from our records.
</p>
<br/>
<p>
    To activate this account, please click the following link within the next
    {{ expiration_days }} days:
</p>

<p>
    <a href="https://{{site.domain}}{% url 'accounts:registration_activate' activation_key %}">
        https://{{site.domain}}{% url 'accounts:registration_activate' activation_key %}
    </a>
</p>
<br/>
<p>
    Sincerely, <br/>
    {{ site.name|capfirst }} Management
</p>
</body>

</html>


{% comment %}
**registration/activation_email.html**

Used to generate the html body of the activation email. Should display a
link the user can click to activate the account. This template has the
following context:

``activation_key``
    The activation key for the new account.

``expiration_days``
    The number of days remaining during which the account may be
    activated.

``site``
    An object representing the site on which the user registered;
    depending on whether ``django.contrib.sites`` is installed, this
    may be an instance of either ``django.contrib.sites.models.Site``
    (if the sites application is installed) or
    ``django.contrib.sites.requests.RequestSite`` (if not). Consult `the
    documentation for the Django sites framework
    <http://docs.djangoproject.com/en/dev/ref/contrib/sites/>`_ for
    details regarding these objects' interfaces.

``user``
    The new user account

``request``
    ``HttpRequest`` instance for better flexibility.
    For example it can be used to compute absolute register URL:

        http{% if request.is_secure %}s{% endif %}://{{ request.get_host }}{% url 'registration_activate' activation_key %}

    or when using Django >= 1.7:

        {{ request.scheme }}://{{ request.get_host }}{% url 'registration_activate' activation_key %}
{% endcomment %}

article/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}


    <div class="medium-6 medium-centered large-4 large-centered">
        {% if next %}
            {% if user.is_authenticated %}
                <p class="errorlist">Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
            {% else %}
                <p class="errorlist">Please login to see this page.</p>
            {% endif %}
        {% endif %}
        <div class="callout secondary">
            <form method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <h4 class="text-center">Sign in to your account</h4>
                {% for field in form %}
                    <div class="fieldWrapper">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="errorlist">{{ error }}</span>
                            <br/>
                        {% endfor %}

                    </div>
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <span class="errorlist">{{ error }}</span>
                {% endfor %}
                <p class="text-center">
                    <button type="submit" class="button expand" name="page_search">Log in</button>
                </p>
                <a href="{% url 'accounts:reset' %}">Forgot your password?</a>
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>

{% endblock content %}
{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

article/accounts/templates/accounts/registration_form.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}Registration{% endblock %}

{% block content %}
<div class="callout success end pass-help show-for-small-only">
    <p>All fields are required</p>
    <p>Username must be bla bla</p>
</div>

<div class="row">
    <div class="medium-7 large-5 columns callout secondary">
    <h3 class="text-center">Register for a new account</h3>
    <form method="POST" action="" novalidate id="registration_form">
        {% csrf_token %}
        {{ form.non_field_errors }}
            <div class="fieldWrapper">
                <label for="{{ form.username.id_for_label }}">Username: *</label>
                {{ form.username|add_class:"thefield" }}
                <label id="client_username" class="ajaxcheck errorlabel"></label>
                {% for error in form.username.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>

            <div class="fieldWrapper">
                <label for="{{ form.email.id_for_label }}">Email: *</label>
                {{ form.email|add_class:"thefield" }}
                <label id="client_email" class="ajaxcheck errorlabel"></label>
                {% for error in form.email.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>

            <div class="fieldWrapper">
                <label for="{{ form.password1.id_for_label }}">Password: *</label>
                {{ form.password1|add_class:"thefield" }}
                <label id="client_password1" class="ajaxcheck errorlabel"></label>
                {% for error in form.password1.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>

            <div class="fieldWrapper">
                <label for="{{ form.password2.id_for_label }}">Confirm password: *</label>
                {{ form.password2|add_class:"thefield" }}
                <label id="client_password2" class="ajaxcheck errorlabel"></label>
                {% for error in form.password2.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>

            <div class="fieldWrapper">
                <label for="{{ form.country.id_for_label }}">Country: *</label>
                {{ form.country|add_class:"thefield" }}
                <label id="client_country" class="ajaxcheck errorlabel"></label>
                {% for error in form.country.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>
        <p><button type="submit" class="button">Submit</button></p>
    </form>

    </div>
    <div class="medium-4 large-4 columns callout success end pass-help show-for-medium">
        <p>All fields are required</p>
        <p>Your password must contain at least 6 characters</p>
        <p>Your password cannot be entirely numeric.</p>
    </div>
</div>

{% endblock %}


{% comment %}
**registration/registration_form.html**
Used to show the form users will fill out to register. By default, has
the following context:

``form``
    The registration form. This will be an instance of some subclass
    of ``django.forms.Form``; consult `Django's forms documentation
    <http://docs.djangoproject.com/en/dev/topics/forms/>`_ for
    information on how to display this in a template.
{% endcomment %}

article/accounts/templates/accounts/reset.html
{% extends 'base.html' %}
{% block title %}Reset Password{% endblock %}

{% block content %}
    <div class="large-5 callout secondary">
        <h3>Reset password</h3>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% for error in field.errors %}
                        <span class="errorlist">{{ error }}</span>
                        <br/>
                    {% endfor %}
                </div>
            {% endfor %}
            <p><button type="submit" class="button">Reset password</button></p>
        </form>
</div>

{% endblock content %}

article/accounts/templates/accounts/reset_confirm.html
{% extends 'base.html' %}
{% block title %}Set New Password{% endblock %}

{% block content %}
    {% if validlink %}
    <div class="row">
        <div class="small-4 columns callout secondary">
            <h4 class="text-center">Set a new password</h4>
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="errorlist">{{ error }}</span>
                            <br/>
                        {% endfor %}

                    </div>
                {% endfor %}
                <p><button type="submit" class="button">Set password</button></p>
            </form>
        </div>
        <div class="small-4 columns callout success end pass-help">
            <p>Your password must contain at least 6 characters</p>
            <p>Your password can't be entirely numeric.</p>
        </div>
    </div>
    {% else %}
        <p>This reset link is no longer valid!</p>
        <p>Please write your email address <a href="{% url "accounts:reset" %}">here</a> and we will send you a new valid reset link</p>
    {% endif %}
{% endblock content %}

article/accounts/templates/accounts/reset_done.html
{% extends 'base.html' %}
{% block title %}Password reset done{% endblock %}

{% block content %}
<p>
    We have sent you an email with a link to reset your password. Please check
    your email and click the link to continue.
</p>
</div>

{% endblock content %}

article/accounts/templates/accounts/reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url "accounts:reset_confirm" uidb64=uid token=token %}

If you did not ask for the password change just ignore this email.