article/accounts/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views  # ???
from .decorators import anonymous_required

from .views import MyRegistrationView, MyActivationView

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', auth_views.logout, {'template_name': 'accounts/logout.html', 'next_page': 'sth:index'},
        name="logout"),
    url(r'^reset/$', auth_views.password_reset, {'template_name': 'accounts/reset.html',
                                                 "email_template_name": 'accounts/reset_email.html',
                                                 "subject_template_name": 'accounts/reset_subject.txt',
                                                 "post_reset_redirect": reverse_lazy('accounts:reset_done')},
        name='reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, {'template_name': 'accounts/reset_done.html'},
        name='reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm, {"template_name": 'accounts/reset_confirm.html',
                                            "post_reset_redirect": reverse_lazy('accounts:login')},
        name='reset_confirm'),
]


registrationpatterns = [
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           MyActivationView.as_view(),
                           name='registration_activate'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),

                       url(r'^register/$', MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^checkavailability/$', views.checkavailability),
                       ]

urlpatterns += registrationpatterns

article/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^badabum/', admin.site.urls),
    url(r'', include('sth.urls', namespace='sth')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^info/', include('info.urls', namespace='info')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/sth/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'articles/$', views.article_list, name="articles"),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[\w-]+)$', views.article_comments, name='article_comments'),
    url(r'^ajaxrating/$', views.ajaxrating, name="ajaxrating"),
]

article/templates/base.html
{% load static from staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} | NewsSite</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% comment %}
        {% compress css %}
            <link href="{% static 'scss/app.scss' %}" media="screen, projection" rel="stylesheet" type="text/x-scss" />
        {% endcompress %}
        {% endcomment %}
        <link href="{% static 'dist/css/app.a187ab7ccc61.css' %}" rel="stylesheet" />



        {% comment %}
        {% compress js %}
            <script type="text/javascript" charset="utf-8">
            $(document).ready(function() {
                $(document).foundation();
            })
            </script>
            <script src="{% static 'magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
            <script src="{% static 'js-cookie/src/js.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
            <script src="{% static 'users/following.js' %}" type="text/javascript" charset="utf-8"></script>
            <script src="{% static 'sth/rating.js' %}"></script>
            <script src="{% static 'accounts/registration.js' %}" type="text/javascript" charset="utf-8"></script>
        {% endcompress %}
        {% endcomment %}
        {% block head %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="large-10 large-centered no-pad-left">
                <h1>News site</h1>
            </div>
        <div class="title-bar show-for-small-only">
            <div class="title-bar-left" data-responsive-toggle="left-menu">
                <button class="menu-icon" type="button" data-toggle></button>
                <div class="title-bar-title">Menu</div>
            </div>
            <div class="title-bar-right" data-responsive-toggle="right-menu">
                {% if request.user.is_authenticated %}
                    <div class="title-bar-title">{{ user.username }}</div>
                {% else %}
                    <div class="title-bar-title">Login/Register</div>
                {% endif %}
                <button class="menu-icon" type="button" data-toggle></button>
            </div>
        </div>

            <div class="top-bar-container">
                <div class="top-bar large-10 large-centered">
                    <div class="top-bar-left element-l" >
                        <ul id="left-menu" class="vertical medium-horizontal menu">
                            <li><a href="{% url 'sth:index' %}">Home</a></li>
                            <li><a href="{% url 'sth:articles' %}">Articles</a></li>
                            <li><a href="{% url 'info:info' %}">Info</a></li>
                        </ul>
                    </div>
                    <div class="top-bar-right element-r">
                        <ul id="right-menu" class="vertical medium-horizontal menu">
                            {% if request.user.is_authenticated %}
                                <li class="show-for-medium"><a href="{% url 'users:user_details' user.username %}">{{ user.username }}</a></li>
                                <li class="show-for-small-only"><a href="{% url 'users:user_details' user.username %}">About me</a></li>
                                <li class="show-for-small-only"><a href="{% url 'users:user_comments' user.username %}">Comments</a></li>
                                <li class="show-for-small-only"><a href="{% url 'users:user_settings' %}">Settings</a></li>
                                <li class="show-for-small-only"><a href="{% url 'users:password_change' %}">Change Password</a></li>
                                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a href="{% url 'accounts:registration_register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </header>

        <div id="layout" class="main large-10 large-centered">
            {% block content %}

            {% endblock content %}

            <div id="layout_footer"></div>
        </div>
        <div id='footer'>
            <div class="large-10 large-centered">
                <a href="{% url "info:contact_form" %}">Contact us</a>
            </div>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
        <script>
            // Fallback to loading jQuery from a local path if the CDN is unavailable
            (window.jQuery || document.write('<script src="{% static 'jquery/dist/jquery.min.js' %}"><\/script>'));
        </script>

        <script src="{% static 'dist/js/f02bcb9c2b0f.js' %}"></script>
        <script src="{% static 'dist/js/o4d6ca65ef46.js' %}"></script>

        {% block jscript %}{% endblock %}
    </body>
</html>