article/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^badabum/', admin.site.urls),
    url(r'', include('sth.urls', namespace='sth')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^info/', include('info.urls', namespace='info')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/sth/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'articles/$', views.article_list, name="articles"),
    url(r'^article/(?P<article_id>[0-9]+)/(?P<slug>[\w-]+)$', views.article_comments, name='article_comments'),
    url(r'^ajaxrating/$', views.ajaxrating, name="ajaxrating"),
]

article/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/about/$', views.user_details, name="user_details"),
    url(r'^settings/$', views.settings_view, name="user_settings"),
    url(r'^(?P<username>[\w.@+-]+)/comments/$', views.UserCommentListView.as_view(), name="user_comments"),
    url(r'^settings/password/change/$', views.change_password, name='password_change'),

    url(r'^to/settings/$', views.to_settings, name="to_settings"),
    url(r'^ajaxfollowing/$', views.ajaxfollowing,),
]

article/users/models.py
from django.db import models
from settings import base
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.core.urlresolvers import reverse


class UserProfile(models.Model):
    user = models.OneToOneField(base.AUTH_USER_MODEL)
    about_me = models.TextField()
    country = CountryField(blank_label='(select country)')
    relationship = models.ManyToManyField('self', through='Relationship', symmetrical=False)

    def __str__(self):
        return self.user.username


class Relationship(models.Model):
    RELATIONSHIP_FOLLOWING = 1
    RELATIONSHIP_BLOCKED = 2
    RELATIONSHIP_STATUSES = (
        (RELATIONSHIP_FOLLOWING, 'Following'),
        (RELATIONSHIP_BLOCKED, 'Blocked'),
    )

    from_person = models.ForeignKey(UserProfile, related_name='from_people')
    to_person = models.ForeignKey(UserProfile, related_name='to_people')
    rel_status = models.IntegerField(choices=RELATIONSHIP_STATUSES)

article/users/forms.py
from django import forms
from django_countries import countries
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


COUNTRY_CHOICES = [('', 'Select country')] + list(countries)


class UserSettingsForm(forms.Form):
    email = forms.EmailField()
    country = forms.ChoiceField(choices=COUNTRY_CHOICES)
    about_me = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(UserSettingsForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        qs = User.objects.filter(email__iexact=self.cleaned_data['email'])
        if len(qs) == 1 and qs[0].email != self.user.email:
            raise forms.ValidationError(
                _("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']

article/users/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import password_change
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.views.decorators.cache import cache_control
from django.views.generic import ListView
from django.utils.decorators import method_decorator

from .models import *
from .utils import one_user_likes, one_user_comments, insert_following, delete_following
from .forms import UserSettingsForm


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def user_details(request, username):
    up = get_object_or_404(UserProfile, user__username=username)
    user_likes = one_user_likes(username)
    is_followed = 0
    if request.user.is_authenticated() and request.user.is_staff is False:
        try:
            check_rel = Relationship.objects.get(from_person_id=request.user.userprofile.id,
                                                    to_person_id=up.id, rel_status=1)
        except Relationship.DoesNotExist:
            check_rel = None

        if check_rel is not None:
            is_followed = 1
    return render(request, 'users/user_details.html', {'user_profile': up, 'is_followed': is_followed,
                                                    'user_likes': user_likes})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required
def settings_view(request):
    u = request.user
    up = u.userprofile
    user_likes = one_user_likes(u.username)
    if request.method == "POST":
        user_form = UserSettingsForm(request.POST, user=request.user)  # we need user for email check

        if user_form.is_valid():
            email = user_form.cleaned_data['email']
            country = user_form.cleaned_data['country']
            about_me = user_form.cleaned_data['about_me']
            if email != u.email:
                u.email = email
                u.save()

            if up.country != country or up.about_me != about_me:  # if something changed then write else not
                up.country = country
                up.about_me = about_me
                up.save()
            messages.add_message(request, messages.INFO, 'You have successfully changed your settings')
            return HttpResponseRedirect(reverse("users:user_settings"))
    else:
        data = {'email': u.email, 'country': up.country, 'about_me': up.about_me}
        user_form = UserSettingsForm(initial=data, user=request.user)  # we need user for email check
    return render(request, template_name="users/user_settings.html", context={'form': user_form,
                                                                              'user_likes': user_likes,
                                                                              'user_profile': up})


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class UserCommentListView(ListView):
    template_name = 'users/user_comments.html'

    def get_queryset(self):
        queryset = one_user_comments(self.kwargs['username']) #because we need ratio for the comments
        return queryset

    def get_context_data(self, **kwargs):
        context = super(UserCommentListView, self).get_context_data(**kwargs)
        up = get_object_or_404(UserProfile, user__username=self.kwargs['username'])
        context['user_profile'] = up
        context['user_likes'] = one_user_likes(self.kwargs['username'])
        is_followed = 0
        if self.request.user.is_authenticated():
            try:
                check_rel = Relationship.objects.get(from_person_id=self.request.user.userprofile.id,
                                  to_person_id=up.id, rel_status=1)
            except Relationship.DoesNotExist:
                check_rel = None

            if check_rel is not None:
                is_followed = 1

        context['is_followed'] = is_followed
        return context

@login_required()
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def change_password(request):
    user_likes = one_user_likes(request.user.username)
    up = request.user.userprofile
    return password_change(request, template_name='users/user_password_change.html',
        post_change_redirect='users:to_settings',
        password_change_form=PasswordChangeForm,
        extra_context={'pass': True, 'user_likes': user_likes, "user_profile": up})  #likes and profile for sub_menu


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def to_settings(request):
    messages.add_message(request, messages.INFO, 'You have successfully changed your password')
    return HttpResponseRedirect(reverse('users:user_settings'))


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def ajaxfollowing(request):
    if "type" in request.POST:
        if request.POST.get('type') == '1':
            insert_following(request.user.userprofile.id, request.POST.get('user_id'))
        else:
            delete_following(request.user.userprofile.id, request.POST.get('user_id'))

        response_dict = {}
        return HttpResponse(json.dumps(response_dict), content_type='application/javascript')
    else:
        return render(request, 'users/user_details.html', context_instance=RequestContext(request))

article/users/templates/users/sub_menu.html
<div class="sticky-to-main sticky-to-main-top">
<div class="row callout sub-header">
    <div class="large-6 columns">
        <h3>{{ user_profile.user.username }}</h3>
        <p>{{ user_likes.0.ratio }} (+{{ user_likes.0.num_of_likes }} -{{ user_likes.0.num_of_dislikes }})</p>
    </div>
    <div class="large-6 columns">
        {% if user.is_authenticated and user.is_staff == False %}
            {% if user.userprofile.id != user_profile.id %}
                <div>
                    <form method="POST" name="following_buttons">
                        {% csrf_token %}
                        {% if is_followed == 1 %}
                            <input id="followed" type="hidden" name="followed" value="1">
                            <input type="button" value="Unfollow" class="foll alert button" id="0{{ user_profile.id }}">
                            <input type="button" value="Follow" class="foll success button" id="1{{ user_profile.id }}">
                        {% else %}
                            <input id="followed" type="hidden" name="followed" value="0">
                            <input type="button" value="Follow" class="foll success button" id="1{{ user_profile.id }}">
                            <input type="button" value="Unfollow" class="foll alert button" id="0{{ user_profile.id }}">
                        {% endif %}


                    </form>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>

{% if user.is_authenticated %}
    {% if user_profile.user.username == user.username %}
        <ul class="sub-nav menu show-for-medium" role="navigation" title="User Menu List">
    {% else %}
        <ul class="sub-nav menu" role="navigation" title="User Menu List">
    {% endif %}
{% else %}
    <ul class="sub-nav menu" role="navigation" title="User Menu List">
{% endif %}

  <li {{ details|yesno:"class=active," }}><span class="show-for-sr">
      About me</span>
      <a href="{% url 'users:user_details' user_profile.user.username %}">About me</a>
  </li>

  <li {{ comments|yesno:"class=active," }}><a href="{% url 'users:user_comments' user_profile.user.username %}">Comments</a></li>
  {% if user.is_authenticated and user.username == user_profile.user.username %}
      <li {{ settings|yesno:"class=active," }}><a href="{% url 'users:user_settings' %}">Settings</a></li>

      <li {{ password|yesno:"class=active," }}><a href="{% url 'users:password_change' %}">Change Password</a></li>
  {% endif %}
</ul>
</div>

article/users/templates/users/user_comments.html
{% extends "base.html" %}
{% load opinion_extras %}
{% load staticfiles %}
{% load compress %}
{% block title %}{{ user_profile.user.username }}'s comments{% endblock %}

{% block head %}{% endblock %}

{% block content %}

{% include "users/sub_menu.html" with comments=1 %}

{% if object_list|length == 0 %}
    <p>No comments to show</p>
{% else %}
    {% for comment in object_list %}
        <h5>{{ comment.article_headline }}</h5>
        <div class="large-8 medium-10 callout warning">
            <div class="row">
                <div class="small-10 columns no-pad-left" >
                    <b><a href="{% url 'users:user_details' comment.username %}">{{ comment.username }}</a></b>
                    <p class="details">{{ comment.comment_date|ago }}</p>
                </div>
                <div class="small-2 columns">
                       <span id="ratio{{ comment.id }}" class="rat">{{ comment.ratio }}</span><br/>
                       <span id="likes{{ comment.id }}" class="succ">+{{ comment.likes }}</span>
                       <span id="dislikes{{ comment.id }}" class="war">-{{ comment.dislikes }}</span>
                </div>
            </div>
            <span><b>{{ comment.comment_headline }}</b></span>
                <p class="content">{{ comment.content|linebreaks }}</p>
        </div>
    <br/>
    {% endfor %}

{% endif %}

{% endblock %}

article/users/templates/users/user_details.html
{% extends "base.html" %}
{% load opinion_extras %}
{% load staticfiles %}
{% load compress %}

{% block title %}{{ user_profile.user.username }}{% endblock %}
{% block head %}{% endblock %}

{% block content %}
    {% include "users/sub_menu.html" with details=1 %}

    <div class="medium-4">
        <table>
            <tr>
                <td>Country:</td>
                <td>{{ user_profile.country.name }}</td>
            </tr>
            <tr>
                <td>Member since:</td>
                <td>{{ user_profile.user.date_joined|ago }}</td>
            </tr>
        </table>
    </div>
    <div class="row">
        <div class="large-9 columns">
            <h6>About me</h6>
            <p> {{ user_profile.about_me|linebreaks }} </p>
            <br/>
        </div>
        <div class="large-3 show-for-large columns">

        </div>
    </div>

{% endblock content %}

article/users/templates/users/user_password_change.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Change password{% endblock %}

{% block content %}


{% include "users/sub_menu.html" with password=1 %}


<div class="callout success end pass-help show-for-small-only">
    <p>All three fields are required</p>
    <p>Your password must contain at least 6 characters</p>
    <p>Your password can't be entirely numeric.</p>
</div>

    <div class="row">
        <div class="medium-5 columns callout secondary">
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        <label for="{{ field.id_for_label }}">{{ field.label }} * </label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="errorlist">{{ error }}</span>
                            <br/>
                        {% endfor %}

                    </div>
                {% endfor %}
                <p><button type="submit" class="button">Change password</button></p>
            </form>
        </div>
        <div class="medium-5 large-4 columns callout success end pass-help show-for-medium">
            <p>All three fields are required</p>
            <p>Your password must contain at least 6 characters</p>
            <p>Your password can't be entirely numeric.</p>
        </div>
    </div>


{% endblock %}


{# This is used by django.contrib.auth #}

article/users/templates/users/user_settings.html
{% extends "base.html" %}
{% block title %}Settings{% endblock %}

{% block content %}

{% include "users/sub_menu.html" with settings=1 %}


<div class="callout success end pass-help show-for-small-only">
    <p>Email and Country are required fields</p>
    <p>About me is not a required field</p>
</div>

<div class="row">
    <div class="medium-7 columns callout secondary">

    {% if messages %}
            {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }} succ"{% endif %}>{{ message }}</p>
            {% endfor %}
    {% endif %}
    <form method="POST" action="{% url 'users:user_settings' %}" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="fieldWrapper">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.label != 'About me' %}
                    *
                    {% endif %}
                </label>
                {{ field }}
                {% for error in field.errors %}
                    <span class="errorlist">{{ error }}</span>
                    <br/>
                {% endfor %}
            </div>
        {% endfor %}
        <p><button type="submit" class="button">Update profile</button></p>
    </form>

    </div>
    <div class="medium-5 large-4 columns callout success end pass-help show-for-medium">
        <p>Email and Country are required fields</p>
        <p>About me is not a required field</p>
    </div>
</div>

{% endblock content %}